/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fac.h"clear

void
fact_prog_1(char *host, int num)
{
    CLIENT *clnt;
    int  *result_1;
    S  factoriel_1_arg;

    factoriel_1_arg.a = num; // Assigner le nombre à la structure

#ifndef	DEBUG
    clnt = clnt_create (host, FACT_PROG, FACT_VERS, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror (host);
        exit (1);
    }
#endif	/* DEBUG */

    result_1 = factoriel_1(&factoriel_1_arg, clnt);
    if (result_1 == (int *) NULL) {
        clnt_perror (clnt, "call failed");
    }

#ifndef	DEBUG
    clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
    char *host;
    int num;

    if (argc < 3) {
        printf ("usage: %s server_host number\n", argv[0]);
        exit (1);
    }
    host = argv[1];
    num = atoi(argv[2]); // Convertir l'argument du nombre en entier
    fact_prog_1 (host, num);
    exit (0);
}


